version: '3.4'

services:
  web-ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    depends_on:
      - yearin-history
      - birthday-collector
      - seq
      - zipkin
    ports:
      - "8000:80"
    restart: on-failure

  yearin-history:
    build:
      context: .
      dockerfile: YearInHistory/Dockerfile
    deploy:
      replicas: 2
    restart: on-failure

  birthday-collector:
    build:
      context: .
      dockerfile: BirthdayCollector/Dockerfile
    deploy:
      replicas: 2
    restart: on-failure
    
  seq:
    image: datalust/seq
    ports:
     - 5341:5341
     - 5342:80
    volumes:
     - rps_seq_data1:/data
    environment:
     - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
      
volumes:
 rps_seq_data1:
  

