version: '3.4'

services:
  web-ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    depends_on:
      - yearinhistory
      - birthdaycollector
    ports:
      - "8000:80"
    restart: on-failure

  yearinhistory:
    build:
      context: .
      dockerfile: YearInHistory/Dockerfile
    deploy:
      replicas: 2
    restart: on-failure

  birthdaycollector:
    build:
      context: .
      dockerfile: BirthdayCollector/Dockerfile
    deploy:
      replicas: 2
    ports:
      - "80"
    restart: on-failure

  

