
services:
  web-ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    depends_on:
      - birthday-service
      - yearinhistory-service
      - seq
      - zipkin
    ports:
      - "8000:80"
    image: wehba/lifetimeline-web-ui
    restart: on-failure
    

  yearinhistory-service:
    build:
      context: .
      dockerfile: YearInHistory/Dockerfile
    deploy:
      replicas: 2
    image: wehba/lifetimeline-yearinhistory-service
    restart: on-failure

  birthday-service:
    build:
      context: .
      dockerfile: BirthdayCollector/Dockerfile
    deploy:
      replicas: 2
    image: wehba/lifetimeline-birthday-service
    restart: on-failure
    
  seq:
    image: datalust/seq
    ports:
     - 5341:5341
     - 5342:80
    volumes:
     - rps_seq_data1:/data
    environment:
     - ACCEPT_EULA=Y

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
      
volumes:
 rps_seq_data1:
  

